### ISSUE TITLE
FOREACH_NO_BOTS not working

### ISSUE THREAD

**Issue by CiprianN23** [karimcambridge/SAMP-foreach#7]
I dont need NPC and Characters iterators and i use FOREACH_NO_BOTS but from last updates its not working anymore

`F:\Stuff\V1-1.1.1\pawno\include\foreach.inc(619) : error 017: undefined symbol "Bot@YSII_Cg"
F:\Stuff\V1-1.1.1\pawno\include\foreach.inc(619) : error 017: undefined symbol "Bot@YSII_Ag"
F:\Stuff\V1-1.1.1\pawno\include\foreach.inc(620) : error 017: undefined symbol "Character@YSII_Cg"
F:\Stuff\V1-1.1.1\pawno\include\foreach.inc(620) : error 017: undefined symbol "Character@YSII_Ag"
F:\Stuff\V1-1.1.1\pawno\include\foreach.inc(718) : error 017: undefined symbol "Bot@YSII_Cg"
F:\Stuff\V1-1.1.1\pawno\include\foreach.inc(718) : error 017: undefined symbol "Bot@YSII_Ag"
F:\Stuff\V1-1.1.1\pawno\include\foreach.inc(719) : error 017: undefined symbol "Character@YSII_Cg"
F:\Stuff\V1-1.1.1\pawno\include\foreach.inc(719) : error 017: undefined symbol "Character@YSII_Ag"`

Give me this errors , any way to fix it? Or i need to get rid of define?

**Comment by karimcambridge** [comment]
Fixed.

Please redownload https://github.com/karimcambridge/SAMP-foreach/releases/tag/v19.1.
