### ISSUE TITLE
foreach error "IteratorArray"

### ISSUE THREAD

**Issue by JoaquinZc** [karimcambridge/SAMP-foreach#8]
Hola tengo un problema, que es cuando intento declarar un nuevo IteratorArray me da el siguiente error

`(718) : error 001: expected token: "-identifier-", but found "-integer value-"`

The line is..

`new IteratorArray:InEdificio[MAX_EDIFICIORENTA]<MAX_PLAYERS>;`

I just want to know why this happens?

**Comment by karimcambridge** [comment]
You have a bug elsewhere in your script.
